"""Minimal backend i18n helpers for user-facing analysis messages."""

from collections.abc import Mapping


Locale = str

_IT = {
  "errors.integrity_generic": "Errore di integrita' del circuito",
  "errors.job_not_found": "Job non trovato",
  "errors.empty_circuit": "Circuito vuoto: aggiungi almeno un componente.",
  "errors.dangling": "Errore di integrita': componenti/rami scoperti ({names}{suffix}).",
  "errors.disconnected": "Errore di integrita': il circuito non e' completamente interconnesso.",
  "errors.missing_param": "Parametro mancante per {component_type} ({component_id})",
  "errors.unknown_voltage_source": "Tensione del generatore non nota ({component_id})",
  "errors.unknown_current_source": "Corrente del generatore non nota ({component_id})",
  "errors.unsupported_component": "Tipo componente non supportato ({component_id})",
  "errors.invalid_value": "Valore non valido per {label}",
  "errors.no_analyzable_bipoles": "Dopo contrazione dei fili non restano bipoli analizzabili.",
  "errors.lcapy_missing": "Lcapy non installato. Esegui: pip install lcapy",
  "errors.no_fundamental_mesh": "Nessuna maglia fondamentale trovata (grafo senza coalbero).",
  "errors.invalid_analysis_params": "Parametri non validi per analisi.",
  "errors.run_empty_circuit": "Circuito vuoto: impossibile eseguire analisi.",
  "analysis.mesh_completed": "Analisi alle maglie completata",
  "analysis.nodal_completed": "Analisi nodale completata",
  "analysis.mesh_output": "Output generato da mesh_analysis.py",
  "analysis.nodal_title": "Analisi nodale (Lcapy)",
  "analysis.mesh_step_1": "1) Costruzione equazione di maglia (LKT)",
  "analysis.mesh_step_2": "2) Vincoli generatori di corrente / supermaglie",
  "analysis.mesh_step_3": "3) Forma matriciale",
  "analysis.mesh_step_4": "4) Risoluzione del sistema",
  "analysis.mesh_step_5": "5) Correnti di ramo",
  "analysis.mesh_no_constraints": "Nessun vincolo",
  "analysis.mesh_no_solution": "Nessuna soluzione",
  "analysis.mesh_no_relation": "Nessuna relazione",
  "analysis.mesh_graph_note_fundamental": "Maglie fondamentali: {count}",
  "analysis.mesh_graph_note_constraints": "Vincoli da generatori di corrente: {count}",
  "analysis.mesh_graph_note_supermeshes": "Supermaglie rilevate: {count}",
  "analysis.mesh_graph_note_auto": "I versi di maglia sono assegnati automaticamente.",
  "analysis.mesh_balance_ok": "Il circuito e' energeticamente bilanciato",
  "analysis.mesh_balance_not_ok": "Il circuito non e' energeticamente bilanciato",
  "analysis.mesh_unknown_powers": "attenzione: presenti {count} potenze ignote",
} 

_EN = {
  "errors.integrity_generic": "Circuit integrity error",
  "errors.job_not_found": "Job not found",
  "errors.empty_circuit": "Empty circuit: add at least one component.",
  "errors.dangling": "Integrity error: dangling components/branches ({names}{suffix}).",
  "errors.disconnected": "Integrity error: the circuit is not fully interconnected.",
  "errors.missing_param": "Missing parameter for {component_type} ({component_id})",
  "errors.unknown_voltage_source": "Unknown source voltage ({component_id})",
  "errors.unknown_current_source": "Unknown source current ({component_id})",
  "errors.unsupported_component": "Unsupported component type ({component_id})",
  "errors.invalid_value": "Invalid value for {label}",
  "errors.no_analyzable_bipoles": "No analyzable dipoles remain after wire contraction.",
  "errors.lcapy_missing": "Lcapy is not installed. Run: pip install lcapy",
  "errors.no_fundamental_mesh": "No fundamental mesh found (graph without cotree).",
  "errors.invalid_analysis_params": "Invalid analysis parameters.",
  "errors.run_empty_circuit": "Empty circuit: analysis cannot run.",
  "analysis.mesh_completed": "Mesh analysis completed",
  "analysis.nodal_completed": "Nodal analysis completed",
  "analysis.mesh_output": "Output generated by mesh_analysis.py",
  "analysis.nodal_title": "Nodal analysis (Lcapy)",
  "analysis.mesh_step_1": "1) Mesh equation construction (KVL)",
  "analysis.mesh_step_2": "2) Current-source constraints / supermeshes",
  "analysis.mesh_step_3": "3) Matrix form",
  "analysis.mesh_step_4": "4) System solution",
  "analysis.mesh_step_5": "5) Branch currents",
  "analysis.mesh_no_constraints": "No constraints",
  "analysis.mesh_no_solution": "No solution",
  "analysis.mesh_no_relation": "No relation",
  "analysis.mesh_graph_note_fundamental": "Fundamental meshes: {count}",
  "analysis.mesh_graph_note_constraints": "Current-source constraints: {count}",
  "analysis.mesh_graph_note_supermeshes": "Detected supermeshes: {count}",
  "analysis.mesh_graph_note_auto": "Mesh directions are assigned automatically.",
  "analysis.mesh_balance_ok": "The circuit is energetically balanced",
  "analysis.mesh_balance_not_ok": "The circuit is not energetically balanced",
  "analysis.mesh_unknown_powers": "warning: {count} unknown powers are present",
}

_TRANSLATIONS = {"it": _IT, "en": _EN}


def locale_from_options(options: Mapping[str, object] | None) -> Locale:
  raw = options.get("locale") if options else None
  return "en" if raw == "en" else "it"


def tr(locale: Locale, key: str, **kwargs: object) -> str:
  bundle = _TRANSLATIONS["en" if locale == "en" else "it"]
  template = bundle.get(key, key)
  return template.format(**kwargs)
